services:
  fsd:
    image: ghcr.io/renorris/openfsd:fsd-latest
    pull_policy: never
    restart: unless-stopped
    ports:
      - 6809:6809/tcp
    environment:
      DATABASE_SOURCE_NAME: /db/openfsd.db?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)
      DATABASE_AUTO_MIGRATE: true
    volumes:
      - db:/db

  web:
    image: ghcr.io/renorris/openfsd:web-latest
    pull_policy: never
    restart: unless-stopped
    environment:
      DATABASE_SOURCE_NAME: /db/openfsd.db?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)
      FSD_HTTP_SERVICE_ADDRESS: http://fsd:13618
    volumes:
      - db:/db

  caddy:
    image: caddy:2
    pull_policy: missing
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
      ACME_EMAIL: ${ACME_EMAIL}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db:
  caddy_data:
  caddy_config:
