# Builder layer
FROM golang:1.24 AS build

WORKDIR /go/src/fsdweb

# Download dependencies
COPY go.mod go.sum ./

RUN go mod download

# Build
COPY . .

ENV GOCACHE=/root/.cache/go-build
ENV CGO_ENABLED=0
RUN --mount=type=cache,target="/root/.cache/go-build" cd web && go build -o /go/bin/fsdweb

# Runner layer
FROM alpine:latest

RUN addgroup -g 2001 nonroot && \
    adduser -u 2001 -G nonroot -D nonroot && \
    mkdir /db && chown -R nonroot:nonroot /db

COPY --from=build --chown=nonroot:nonroot /go/bin/fsdweb /

USER 2001:2001

CMD ["/fsdweb"]
